# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
loom_version=1.11-SNAPSHOT
fabric_version=0.92.6+1.20.1

# Mod Properties
mod_version=0.0.4
maven_group=ooo.foooooooooooo
archives_base_name=upc

# Dependencies
energy_version=3.0.0
wthit_version=8.6
modmenu_version=7.2.1
megane_version=8.4.0
badpackets_version=0.4.1
athena_version=3.1.2
mi_version=1.8.6
cloth_config_version=5.0.38
omega_config_version=1.4.1-1.20.1
magna_version=1.10.1+1.20.1
pal_version=1.8.0
rea_version=2.1.1
